Feature/mvp
yevhentretiakov/nearbycafe pull request #3
Opened 2022-08-24 10:43 UTC by yevhentretiakov

Changed project architecture to MVP+R.

2022-08-26 07:08 UTC, Nikitax23 requested changes
В целом - нормально и правильно. 
Есть небольшие отклонения от архитектуры, которые мы обсудим. Ничего критичного, но в некоторых моментах немного по-другому нужно.

2022-08-26 07:08 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/Map/View/MapViewController.swift
> +            zoom: self.zoomLevel
здесь необязательно было self использовать. 
это не ошибка, просто было без self, и так же само будет с self) не понимаю этого изменения

2022-08-26 07:08 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/Map/View/MapViewController.swift
> +    func updateMap(latitude: Double, longitude: Double) {
вот если в случае не с таблицей, то презентер может передать places через такой метод view-протокола. 

например, `func updateMap(with places: [PlaceModel], userLocation: Location)` 

PS. 
Тоже необязательно обворачивать это в структуру Location, но было бы удобно использовать структуру, а не два отдельных параметра. Они все равно друг без друга не существуют. Всегда есть latitude и longitude

2022-08-26 09:04 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/Map/View/MapViewController.swift
> +        DispatchQueue.main.async {
`DispatchQueue.main.async`
думаю, эти вещи можно оставить в презентере. 
Там, где вызывается метод вью протокола

2022-08-26 09:08 UTC, yevhentretiakov commented on NearbyCafe/NearbyCafe/Modules/Map/Presenter/MapViewPresenter.swift
> +                    completion()
1) мне показалось больше возможностей переиспользовать, места получили и дальше любое действие подставить можно 
2) и еще в случае если вызывать просто внутри, вместо `completion()`, то получиться что метод `getPlaces` выполняет два действия: получает сами места по сети и потом еще вызывает обновление карты на вью, а насколько я понял `SRP` принцип из солид, то две задачи в один метод не очень хорошо пихать или это не про этот случай?

2022-08-26 12:30 UTC, yevhentretiakov commented on NearbyCafe/NearbyCafe/Modules/List/Presenter/ListViewPresenter.swift
> +    init(view: ListViewController, places: [PlaceModel], router: RouterProtocol) {
1) Я не стал изначально создавать `ListViewProtocol` потому что он не имел никаких методов или свойств и передал просто как `ListViewController`. А нужно ли создавать в случае чего пустой `ViewProtoсol` если он не имеет методов?

2) Сейчас исправил и сделал через `ListViewProtocol` с методом `updateView()`. Вызываю его в инициализаторе `ListViewPresenter`. Он в свою очередь вызывает `tableView.reloadData()` на `ListViewController` и после этого происходит `unexpectedly found nil while unwrapping an Optional value`. 

Я так понял это происходит из-за того что в билдере такой порядок действий 
1. создается вью
2. создается презентер с этим вью 
3. задается ссылка на презентер, после чего уже можно у презентера вызывать методы нужные для dataSource `presenter.getItemsCount() ` и `presenter.getItem(at: indexPath.row)`

Но попытка `updateView()` произойдет после 2го шага, до того 3го шага, до того как будет возможность получить что то из презентера и из-за этого упадет. 

Верно? 
И как оно тогда сейчас вообще подтягивает данные само без всяких релоадов и показывает все?)

2022-08-26 14:11 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/List/Presenter/ListViewPresenter.swift
> +    init(view: ListViewController, places: [PlaceModel], router: RouterProtocol) {
обсудили

2022-08-29 20:14 UTC, Nikitax23 requested changes
много моментов нужно поправить

2022-08-29 20:14 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Managers/LocationManager/LocationManager.swift
> +    var delegate: LocationManagerDelegateProtocol? { get set }
делегат не выносится в протокол как проперти. 
если ты хочешь задавать делегат, то сделай метод `setDelegate`. зачем тебе `getter` делегата?

2022-08-29 20:14 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Managers/LocationManager/LocationManager.swift
>      func startUpdatingLocation()
`startUpdatingLocation`
ты уверен, что текущее название хорошее для данного метода?
метод же не только делает  startUpdatingLocation, а и много другого. стоит подумать над этим названием

2022-08-29 20:14 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/List/Builder/ListModuleBuilder.swift
>      func createListModule(places: [PlaceModel]) -> UIViewController
`func createListModule(places: [PlaceModel])`

=> 

`func createListModule(with places: [PlaceModel])`

2022-08-29 20:14 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/List/Builder/ListModuleBuilder.swift
>  protocol ListModuleBuilderProtocol {
`ListModuleBuilderProtocol`
не обязательно в конце названия приписывать слово `Protocol`. 
ты же не приписываешь суффикс class для классов и struct для структур)))) 
ты видел хоть один протокол у Apple ,  который заканчивается словом protocol? 

лучше протокол называть `ListModuleBuilder`, а реализацию - то же самое , только с префиксом `Default` ( так как это может быть дефолтная реализация, и она может быть заменена любой другой в будущем)

2022-08-29 20:14 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/List/Presenter/ListViewPresenter.swift
> +    func dismiss()
почему `dismiss`, если у тебя экран показывается не модально? почему не `close`?

2022-08-29 20:14 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/List/Presenter/ListViewPresenter.swift
> +    private let router: ListModuleRouterProtocol
то же самое , касательно слова protocol и в роутерах

2022-08-29 20:14 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/Map/Builder/MapModuleBuilder.swift
> +protocol MapModuleBuilderProtocol {
то же самое с названиями протокола и класса . 
почему класс не финальный? разве планируешь еще наследоваться от него? 

то же самое в других созданных классах

2022-08-29 20:14 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/Map/Builder/MapModuleBuilder.swift
> +        let googleServiceManager = GoogleServicesManager()
гугл сервис тут не нужен

2022-08-30 09:22 UTC, yevhentretiakov commented on NearbyCafe/NearbyCafe/Application/SceneDelegate.swift
> +        window?.rootViewController = UINavigationController(rootViewController: MapModuleBuilder().createMapModule())
Вынес, но почему так лучше?

2022-08-30 11:23 UTC, yevhentretiakov commented on NearbyCafe/NearbyCafe/MainRouter/MainRouter.swift
> +        if isModal || navigationController == nil {
По 2му пункту, а что если` isModal = false` , но и `navigationController` не будет чтобы можно было запушить и в этом случае ничего не произойдет же

2022-09-01 06:56 UTC, Nikitax23 requested changes
есть пара моментов к оптимизации. 
в целом - хорошая работа!

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/BaseRouter/BaseRouter.swift
> +    func popToViewController(viewController: UIViewController, animated: Bool, completion: EmptyBlock?)
`func popToViewController(viewController: UIViewController, animated: Bool, completion: EmptyBlock?)`

в случае, когда у тебя в названии метода и названии параметра есть одно и то же слово, как "viewController", то следует либо убирать это слово из названия метода (что я бы предпочел), либо делать вот так 

`func popToViewController(_ viewController: UIViewController, animated: Bool, completion: EmptyBlock?)`

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/BaseRouter/BaseRouter.swift
> +                completion?()
можно было этот комплишн просто передать как параметр, разве не так?

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/BaseRouter/BaseRouter.swift
> +            receiveTransitionCompletion {
```
navigationController?.pushViewController(viewController, animated: animated)
            receiveTransitionCompletion {
                completion?()
            }
```

вот тут как бы всё правильно, но это нужно хендлить в екстеншне `UINavigationController`, а не как у тебя - в роутере, в каждом методе, где тебе это пригодится.

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/BaseRouter/BaseRouter.swift
> +        receiveTransitionCompletion {
то же самое здесь

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/BaseRouter/BaseRouter.swift
> +        receiveTransitionCompletion {
то же самое здесь

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/BaseRouter/BaseRouter.swift
> +        if viewController.isModal {
а навигейшн контроллер тоже может быть isModal . 
у этого роутера есть viewController. он может быть с навигейшном, а может быть - без. 
и когда контроллер без навигейшна, то могут запрезентить его. 
а когда с навигейшном , то могут запрезентить навигейшн) 
это тоже надо обработать

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/BaseRouter/BaseRouter.swift
> +        receiveTransitionCompletion {
то же самое с комплишном

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/BaseRouter/BaseRouter.swift
> +        if let coordinator = navigationController?.transitionCoordinator {
вот это надо перенести в extension навигейшн контроллера. 

надо продублировать метод push/pop/popTo и тд. 
в них вызывать дефолтные методы навигейшна, и обязательно проверить: 
анимированная ли данная навигация?, и есть ли координатор? 
ты проверяешь только наличие координатора. 

данные условия можно проверить в гвард лете.

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Extensions/UIViewController+Extensions.swift
> +        self.presentingViewController != nil ? true : false
1) 
`self.presentingViewController != nil ? true : false` 
можно заменить просто на 

`self.presentingViewController != nil`

оно ж возвращает `Bool` ) 

2) ты не проверяешь опять навигейшн контроллер. надо проверять

2022-09-01 06:56 UTC, Nikitax23 commented on NearbyCafe/NearbyCafe/Modules/List/Router/DefaultListModuleRouter.swift
> +
1) а у тебя собирается проект? где реализация 
`close` метода? или ты где-то прописал дефолтную реализацию?

2) `func close(animated: Bool, completion: EmptyBlock?)`

не обязательно здесь передавать (принимать) эти параметры, если тебе не нужно контролировать это из-вне для разных случаев. у тебя дефолтный клоуз, и ты можешь задать все нужные параметры прямо внутри роутера. 
только если тебе уже нужно контролировать анимированность, или что-то предпринимать , когда навигация будет завершена, тогда можно выносить это на уровень выше - на уровень протокола.

2022-09-01 14:47 UTC, merged